---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/transactions":
    post:
      summary: Creates a new transaction
      tags:
      - Transactions
      parameters: []
      responses:
        '201':
          description: transaction created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                wallet_id:
                  type: integer
                transaction_type:
                  type: string
                  enum:
                  - credit
                  - debit
                  - transfer
                amount:
                  type: number
                recipient_wallet_id:
                  type: integer
              required:
              - wallet_id
              - transaction_type
              - amount
  "/transactions/{id}":
    get:
      summary: Retrieves a transaction
      tags:
      - Transactions
      parameters:
      - name: id
        in: path
        description: ID of the transaction
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: transaction found
        '404':
          description: transaction not found
  "/users":
    post:
      summary: Creates a user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
              - name
              - email
              - password
    get:
      summary: Retrieves all users
      tags:
      - Users
      responses:
        '200':
          description: users found
  "/users/{id}":
    get:
      summary: Retrieves a user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        description: ID of the user
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: user found
        '404':
          description: user not found
  "/wallets/{wallet_id}/transactions":
    get:
      summary: Retrieves all transactions for a wallet
      tags:
      - Wallet Transactions
      parameters:
      - name: wallet_id
        in: path
        description: ID of the wallet
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: transactions found
        '404':
          description: wallet not found
  "/wallets":
    post:
      summary: Creates a new wallet
      tags:
      - Wallets
      parameters: []
      responses:
        '201':
          description: wallet created
        '422':
          description: wallet already exists
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
              required:
              - user_id
  "/wallets/{id}":
    get:
      summary: Retrieves a wallet
      tags:
      - Wallets
      parameters:
      - name: id
        in: path
        description: ID of the wallet
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: wallet found
        '404':
          description: wallet not found
servers:
- url: http://localhost:3000
  description: Local development server
  variables:
    defaultHost:
      default: http://localhost:3000
